branchName: '${issue.number}-${issue.title,}'
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: question
    skip: true
  - label: '*'
    prefix: issue/
